### ISSUE TITLE
build with gcc 10.x (or newer) ?

### ISSUE THREAD

**Issue by rroulleau** [polarfire-soc/polarfire-soc-buildroot-sdk#5]
Do you plan to support the buildroot-sdk with the latest gcc 10.x (or newer) for the buildroot-sdk? currently the build is using gcc 9.2 
or 
Use glibc 2.33 instead of glibc2.29?

**Comment by ConchuOD** [comment]
sorry for the delay in getting back to you, but yes i do plan on upgrading the version of toolchain components, if not in the next tagged release will be in the one after.
